# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-02-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20200201_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=32, verbose_name='密码'),
        ),
    ]
